### ISSUE TITLE
Fix bug - make run - when running current version

### ISSUE THREAD

**Issue by nlauchande** [nlauchande/bitpred#24]
➜  bitpred git:(develop) make run
mlflow run .
2020/02/05 22:54:04 INFO mlflow.projects: === Building docker image bitpred:9057ff3 ===
2020/02/05 22:54:05 INFO mlflow.projects: === Created directory /var/folders/wh/nv84s8d506x415fsfjn3nplxk2qd0l/T/tmpx0rgww8n for downloading remote URIs passed to arguments of type 'path' ===
2020/02/05 22:54:05 INFO mlflow.projects: === Running command 'docker run --rm -v /Users/natu.lauchande/development/research/bitpred/mlruns:/mlflow/tmp/mlruns -v /Users/natu.lauchande/development/research/bitpred/mlruns/0/d737c38e878649549ff2526d1cd224b5/artifacts:/Users/natu.lauchande/development/research/bitpred/mlruns/0/d737c38e878649549ff2526d1cd224b5/artifacts -e MLFLOW_RUN_ID=d737c38e878649549ff2526d1cd224b5 -e MLFLOW_TRACKING_URI=file:///mlflow/tmp/mlruns -e MLFLOW_EXPERIMENT_ID=0 bitpred:9057ff3 python train.py' in run with ID 'd737c38e878649549ff2526d1cd224b5' === 
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    mlflow.sklearn.log_model(clf, "model_random_forest",registered_model_name="RandomForestModel")
  File "/opt/conda/lib/python2.7/site-packages/mlflow/sklearn.py", line 200, in log_model
    registered_model_name=registered_model_name)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/models/__init__.py", line 87, in log
    registered_model_name)
  File "/opt/conda/lib/python2.7/site-packages/mlflow/tracking/_model_registry/fluent.py", line 34, in register_model
    raise e
mlflow.exceptions.MlflowException: Model Registry features are not supported by the store with URI: 'file:///mlflow/tmp/mlruns'. Stores with the following URI schemes are supported: ['sqlite', 'http', 'databricks', 'https', 'mysql', 'postgresql', 'mssql'].
2020/02/05 22:54:11 ERROR mlflow.cli: === Run (ID 'd737c38e878649549ff2526d1cd224b5') failed ===
make: *** [run] Error 1

**Comment by nlauchande** [comment]
https://github.com/nlauchande/bitpred/pull/28 - Issue sorted!!!
